### ISSUE TITLE
More than 2 XScreens (in differing layout directions [vert vs hori])

### ISSUE THREAD

**Issue by ghost** [vincenzo85/how-to-Share-Screens-Between-Two-Ubuntu-PCs-with-X11#1]
*This should be a discussion question but discussions aren't enabled.

I've been researching how to get x2x to work with more than 2 XScreens in different "directions." Meaning when you use -North it assumes all XScreens are north of each other. It also works backwards so for example moving to the other machine it will not align the cursor to where you move but rather to where you move in line with the highest XScreen. So from machine 1 DISPLAY=:0.0 it will move to the second machine DISPLAY=:0.2 which is not ideal.

So do you have any idea of syntax in how you can define layout? x2x takes the x root meaning denoting the actual XScreen doesn't work as you'd expect. So ssh -YX user@othermachine x2x -north -noscale -to :0.0 <== goes to :0.2 ==> 0.1 ==> 0.0. Likewise ssh -YX user@othermachine x2x -north -noscale -to :0 does the same, it just grabs the whole root and works backwards.

So for example my layout would be machine 1 DISPLAY=:0 (single XScreen) machine 2 above machine 1 but 3 XScreens horizontal :0.1 left :0.0 center :0.2 right but using -north you have to go up to jump right to left then up more to go left to center.

I can't find anything on how to get x2x to actually adhere to the actual XScreen you want (not XRoot) so you can denote :0.1 west of :0.0, 0.2 east of :0.0 etc.

At present I've inverted the scenario where the machine with the horizontal XScreen layout connects back to the single XScreen machine but this results in some odd screen warping. Hitting say the bottom of the screen jumps you back to the top...just strange. (This also is only possible by inverting which machine has the actual mouse and keyboard too via KM switch.)

**Comment by vincenzo85** [comment]
You can see this repo: https://github.com/vincenzo85/x2x-update

**Comment by nPHYN1T3** [comment]
Thanks, I'll dig through that in a bit. As for your why not Barrier section you might want to note that the why not is because it's a dead project. Now there is only Input-Leap, Desk-Flow and the commercial version Synergy but they are all horribly broken heh.

**Comment by ghost** [comment]
I had made a diagram and a write up about why this updated guide is non-functional but since the instructions read like self contradicting Ai churn I'll just leave this as you don't know how to do this and or this is an Ai account.
